### PR TITLE
[Dummy for Debugging] Test auto merge 3

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit bf370b645776580023c1604f1bb0b69980235da3 has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:hourglass: bf370b645776580023c1604f1bb0b69980235da3 has been merged into the auto branch https://github.com/nekoya/popuko/commit/3c6e23e3805e8a4412cb2f0c4caf1f962f252f7f

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/nekoya/popuko/builds/185443376)

**Comment by popuko** [comment]
:hourglass: Try to merge bf370b645776580023c1604f1bb0b69980235da3 into `master`

**Comment by popuko** [comment]
Could not merge this pull request by:
```
PUT https://api.github.com/repos/nekoya/popuko/pulls/89/merge: 405 Base branch no longer exists []
```

**Pull request closed without merging**
