### PR TITLE
Add 'Why there is no released version?' to README

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@saneyuki r?

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
Try to merge this pull request which has been approved by `nekoya`

**Pull request merged**
