### PR TITLE
[Dummy for Debugging]  Test auto merge 2

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e60009744a495ce78d67365abd1340e1ce30e97b has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time. :sleeping:

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e60009744a495ce78d67365abd1340e1ce30e97b has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e60009744a495ce78d67365abd1340e1ce30e97b has been merged into the auto branch https://github.com/nekoya/popuko/commit/a163cc310d4368e916ad5a65e5a38cac5cc5f299

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/nekoya/popuko/builds/185442971)

**Comment by popuko** [comment]
:hourglass: Try to merge e60009744a495ce78d67365abd1340e1ce30e97b into `master`

**Pull request merged**
