### PR TITLE
[Dummy for Debugging] Test auto merge 4

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit f31d3273ef75b862b39f48b0c28bd37f805f7c0f has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: f31d3273ef75b862b39f48b0c28bd37f805f7c0f has been merged into the auto branch https://github.com/nekoya/popuko/commit/a8b340819838bd1443d257e79d49cfd527f1cf81

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/nekoya/popuko/builds/185445277)

**Comment by popuko** [comment]
:hourglass: Try to merge f31d3273ef75b862b39f48b0c28bd37f805f7c0f into `master`

**Pull request merged**
