### PR TITLE
Test

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r?

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 27a2bbf73d28faad093d017c0bd632adf3f98d73 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 27a2bbf73d28faad093d017c0bd632adf3f98d73 has been merged into the auto branch https://github.com/nekoya/popuko/commit/b229202697f3aa3ca6fb059d0157c3afa5d20946

**Comment by popuko** [comment]
:hourglass: Try to merge 27a2bbf73d28faad093d017c0bd632adf3f98d73

**Pull request merged**
