### PR TITLE
[Dummy for Debugging]  Test auto merge 1

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0d08a4cd60a5ed5289458168b4f8edb180b655f3 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 0d08a4cd60a5ed5289458168b4f8edb180b655f3 has been merged into the auto branch https://github.com/nekoya/popuko/commit/2c35715b03ccb45098c773d46cf56701502538cc

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/nekoya/popuko/builds/185412871)

**Comment by popuko** [comment]
:hourglass: Try to merge 0d08a4cd60a5ed5289458168b4f8edb180b655f3 into `master`

**Pull request merged**
