### PR TITLE
Rename fields related to configurations

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by popuko** [comment]
:umbrella: The latest upstream change (presumably [these](https://github.com/nekoya/popuko/compare/c17446b92099...5ede7dacec25)) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit f8402edba0d5469531516306a267ce816aa84863 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: Try to merge f8402edba0d5469531516306a267ce816aa84863

**Pull request merged**
