### PR TITLE
Enable experimental.auto_merge.try_on_auto_branch by this bot.

### PR DESCRIPTION
**Pull request by saneyuki**
This will be introduced by https://github.com/nekoya/popuko/pull/79

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c30c85a6e605020cf0b0b826d473f68d4652955b has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: Try to merge c30c85a6e605020cf0b0b826d473f68d4652955b

**Pull request merged**
