### PR TITLE
[Dummy for Debugging] Test auto merge 5

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 7564486101a3b444bb117d4bd862f098497aedba has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:hourglass: 7564486101a3b444bb117d4bd862f098497aedba has been merged into the auto branch https://github.com/nekoya/popuko/commit/747fb1eb8fd6642d1630d58d76752a9d53e424f2

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/nekoya/popuko/builds/185445971)

**Comment by popuko** [comment]
:hourglass: Try to merge 7564486101a3b444bb117d4bd862f098497aedba into `master`

**Pull request merged**
