### PR TITLE
Comment the sha of head for the approved pull request.

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 52a78a337a3a55f6cc48b2c4c6aff1d2b5ad3582 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: Try to merge 52a78a337a3a55f6cc48b2c4c6aff1d2b5ad3582

**Pull request merged**
