### PR TITLE
More testing auto merging

### PR DESCRIPTION
**Pull request by saneyuki**
Reverts nekoya/popuko#83

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 786afea80fea71c732eed1f6583cabcbbd2c190a has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 786afea80fea71c732eed1f6583cabcbbd2c190a has been merged into the auto branch https://github.com/nekoya/popuko/commit/6e4161f0c7cb94ecf506bfb0b15545be4e2535da

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 786afea80fea71c732eed1f6583cabcbbd2c190a has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 786afea80fea71c732eed1f6583cabcbbd2c190a has been merged into the auto branch https://github.com/nekoya/popuko/commit/2d02b492d0036a7f1461d04d6d6be3547abc16fe

**Comment by popuko** [comment]
:zap: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/nekoya/popuko/builds/185409034)

**Comment by popuko** [comment]
:hourglass: Try to merge 786afea80fea71c732eed1f6583cabcbbd2c190a into `master`

**Pull request merged**
