### PR TITLE
#45 part 1 - Implement to creating auto branch.

### PR DESCRIPTION
**Pull request by saneyuki**
- This is still experimental feature.
- This patch is just a "part 1"
  - https://github.com/nekoya/popuko/issues/45
- This introduce `repositoryInfo.ExperimentalTryOnAutoBranch()`
 - If it is true, this bot try to creat an auto branch when merge pull
   request.
 - This flag is only enabled if both of experimentalTryOnAutoBranch and
   EnableAutoMerge are true.

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit ae88183052110dc2df96b0ab622cf38c3de3cec6 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: ae88183052110dc2df96b0ab622cf38c3de3cec6 has been merged into the auto branch https://github.com/nekoya/popuko/commit/17454995c0c40ac589356ad649b6c0e358184f22

**Pull request merged**
