### PR TITLE
[Dummy for Debugging] Automerge test 1

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit ac46f81f35a5aca921325ce6c11c0c62f48fc0f6 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: ac46f81f35a5aca921325ce6c11c0c62f48fc0f6 has been merged into the auto branch https://github.com/nekoya/popuko/commit/80578e26fb63c33b1b4545c6db058ca94b1231ca

**Comment by popuko** [comment]
:zap: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/nekoya/popuko/builds/185410641)

**Comment by popuko** [comment]
:hourglass: Try to merge ac46f81f35a5aca921325ce6c11c0c62f48fc0f6 into `master`

**Pull request merged**
